services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ciaboc-keycloak

    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

    ports:
      - "8082:8080"

    volumes:
      - ./themes:/opt/keycloak/themes