parent=keycloak.v2
import=common/keycloak

styles=css/ciaboc.css

# Remove Keycloak outer layout restrictions
kcLoginClass=
kcFormCardClass=
kcHeaderClass=
kcHeaderWrapperClass=

# Keep the normal form classes available
kcFormClass=
kcFormGroupClass=
kcLabelClass=
kcInputClass=
kcFormButtonsClass=
kcButtonClass=